import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PLUGIN_ROOT = resolve(__dirname, "../..");
const OFFICIAL_AGENT_DOC_ROOT = join(
  PLUGIN_ROOT,
  "skills",
  "hero-ui-craft",
  "references",
  "official",
  "react"
);

const AGENT_DOC_ORDER = [
  ["agents", "Official HeroUI React AGENTS.md generated by heroui-cli agents-md. Read this first."],
  ["llms", "Quick HeroUI React documentation index."],
  ["components", "HeroUI React component docs index and component guidance."],
  ["patterns", "HeroUI React patterns, recipes, composition, and theming guidance."],
  ["full", "Complete HeroUI React documentation snapshot. Load only for deep lookup."]
];

const COMPONENT_RULES = [
  {
    match: ["navigation", "sidebar", "nav", "breadcrumb", "route"],
    components: [
      ["Breadcrumbs", "Show hierarchy and detail-page orientation using the official navigation primitive."],
      ["Tabs", "Switch between sibling views within the same workflow."],
      ["Link", "Use for navigational text actions."]
    ]
  },
  {
    match: ["filter", "filters", "search", "command", "picker"],
    components: [
      ["SearchField", "Search-specific input with accessible semantics."],
      ["Select", "Bounded option sets."],
      ["ComboBox", "Searchable option sets when users need typeahead."],
      ["Popover", "Compact secondary filter surfaces."]
    ]
  },
  {
    match: ["data", "table", "list", "records", "orders", "customers"],
    components: [
      ["Table", "Dense comparison and repeated-row workflows."],
      ["Checkbox", "Bulk row selection."],
      ["Pagination", "Long record sets."]
    ]
  },
  {
    match: ["detail", "drawer", "panel", "edit", "inspect"],
    components: [
      ["Drawer", "Inspect or edit an item without losing list context."],
      ["Modal", "Focused blocking decisions or multi-step edits."],
      ["Button", "Primary and secondary commands."]
    ]
  },
  {
    match: ["form", "input", "validated", "validation", "settings"],
    components: [
      ["Form", "Coordinate form submission and validation."],
      ["Fieldset", "Group related fields."],
      ["Input", "General text input."],
      ["TextArea", "Long-form input."],
      ["FieldError", "Inline field-level validation."],
      ["ErrorMessage", "Form-level or field-level error feedback."]
    ]
  },
  {
    match: ["empty", "loading", "error", "success", "state", "feedback", "toast", "notification"],
    components: [
      ["Toast", "Transient feedback after user actions."],
      ["Alert", "Persistent feedback for important states."],
      ["Skeleton", "Layout-preserving loading states."],
      ["Spinner", "Short indeterminate loading states."]
    ]
  },
  {
    match: ["metric", "analytics", "chart", "progress", "status"],
    components: [
      ["Card", "Use only for repeated metrics or genuinely framed content."],
      ["Badge", "Compact status and count marks."],
      ["ProgressBar", "Bounded progress."],
      ["Meter", "Quantitative status ranges."]
    ]
  },
  {
    match: ["toolbar", "actions", "button group", "tooltip"],
    components: [
      ["Toolbar", "Group related commands."],
      ["ButtonGroup", "Cluster mutually related actions."],
      ["Tooltip", "Name icon-only or unfamiliar controls."]
    ]
  }
];

const HERO_UI_SEMANTIC_TOKENS = [
  "bg-background",
  "text-foreground",
  "bg-content1",
  "bg-content2",
  "text-default-500",
  "border-divider",
  "text-primary",
  "bg-primary",
  "text-danger",
  "bg-danger",
  "text-success",
  "bg-success"
];

const REQUIRED_VISUAL_STATES = [
  "default",
  "hover",
  "focus",
  "disabled",
  "loading",
  "empty",
  "error",
  "success",
  "mobile"
];

const REQUIREMENT_SEQUENCE = [
  "粗需求",
  "业务需求",
  "产品需求",
  "信息架构需求",
  "交互需求",
  "状态需求",
  "视觉需求",
  "工程需求",
  "验收需求",
  "HeroUI组件映射",
  "Pencil/Figma视觉确认"
];

const REQUIREMENT_ARTIFACTS = [
  {
    file: "00-requirement-brief.md",
    title: "粗需求澄清",
    layer: "粗需求",
    purpose: "把一句想法拆成目标、范围、用户、约束、未知问题和确认项。",
    requiredSections: ["原始诉求", "目标用户", "核心目标", "范围边界", "待澄清问题", "确认记录"],
    exitCriteria: ["需求目标可复述", "范围内外已写明", "仍未知的问题已列出"]
  },
  {
    file: "01-business-requirements.md",
    title: "业务需求",
    layer: "业务需求",
    purpose: "回答为什么要做、业务成功指标、风险和优先级。",
    requiredSections: ["为什么要做", "业务目标", "成功指标", "业务规则", "约束与风险"],
    exitCriteria: ["每个业务目标都有可观察指标", "关键业务规则已列出"]
  },
  {
    file: "02-product-requirements.md",
    title: "产品需求",
    layer: "产品需求",
    purpose: "回答谁用、完成什么任务、主流程和非目标。",
    requiredSections: ["用户角色", "任务清单", "主工作流", "范围内功能", "非目标"],
    exitCriteria: ["主任务路径明确", "功能优先级明确", "非目标明确"]
  },
  {
    file: "03-information-architecture.md",
    title: "信息架构需求",
    layer: "信息架构需求",
    purpose: "回答内容怎么分组、层级怎么组织、数据对象如何关联。",
    requiredSections: ["信息对象", "层级结构", "导航结构", "数据字段", "内容优先级"],
    exitCriteria: ["每个页面/区域的信息来源明确", "主次层级明确"]
  },
  {
    file: "04-interaction-matrix.md",
    title: "交互需求",
    layer: "交互需求",
    purpose: "回答什么常驻、什么隐藏、点击哪里发生什么、反馈是什么。",
    requiredSections: ["交互矩阵", "触发点", "系统反馈", "权限与限制", "键盘与无障碍"],
    exitCriteria: ["每个主要动作都有触发、结果、反馈", "隐藏/展开/弹层行为明确"]
  },
  {
    file: "05-state-requirements.md",
    title: "状态需求",
    layer: "状态需求",
    purpose: "回答空数据、加载、错误、异常、编辑、成功、禁用和移动态怎么显示。",
    requiredSections: ["空数据", "加载", "错误", "异常", "编辑", "成功", "禁用", "移动态"],
    exitCriteria: ["每个核心组件都有状态覆盖", "异常和错误可被用户理解并处理"]
  },
  {
    file: "06-visual-requirements.md",
    title: "视觉需求",
    layer: "视觉需求",
    purpose: "回答密度、风格、组件样式、信息强调和禁止的视觉味道。",
    requiredSections: ["视觉密度", "版式原则", "组件风格", "颜色语义", "禁止项"],
    exitCriteria: ["视觉方向可执行", "禁止项明确", "移动/桌面密度明确"]
  },
  {
    file: "07-engineering-contract.md",
    title: "工程需求",
    layer: "工程需求",
    purpose: "回答组件拆分、数据结构、响应式、路由、HeroUI官方组件映射和禁止手写UI规则。",
    requiredSections: ["HeroUI官方上下文", "Official Component First", "组件映射", "数据结构", "响应式", "路由", "例外记录"],
    exitCriteria: ["所有可见UI都有HeroUI组件映射或例外", "禁止手写UI条款明确"]
  },
  {
    file: "08-acceptance-contract.md",
    title: "验收需求",
    layer: "验收需求",
    purpose: "回答怎么判断做得对不对，包括功能、视觉、无障碍、截图、测试和HeroUI合规。",
    requiredSections: ["怎么判断做得对不对", "功能验收", "视觉验收", "HeroUI合规", "测试命令", "截图验收"],
    exitCriteria: ["每条验收都可被命令、截图或人工确认", "失败条件明确"]
  },
  {
    file: "09-visual-confirmation-plan.md",
    title: "Pencil/Figma视觉确认计划",
    layer: "Pencil/Figma视觉确认",
    purpose: "定义开发设计图之前必须输出的桌面、移动、组件细节和状态矩阵图片。",
    requiredSections: ["Pencil/Figma", "桌面图", "移动图", "组件细节", "状态矩阵", "用户确认"],
    exitCriteria: ["用户确认导出图片", "每个重要组件的状态已覆盖"]
  }
];

const REQUIREMENT_FILES = REQUIREMENT_ARTIFACTS.map((artifact) => artifact.file);
const REQUIRED_BEFORE_VISUAL = REQUIREMENT_FILES.filter(
  (file) => file !== "09-visual-confirmation-plan.md"
);

const REQUIREMENT_WORKSPACE_ROOT = "docs/full-stack-development/requirements";

const WORKSPACE_STAGE_FILE = "00-stage.json";

const REQUIREMENT_WORKSPACE_ARTIFACTS = [
  {
    file: "01-rough-request.md",
    stage: "rough-intake",
    title: "粗需求澄清",
    prompt:
      "Capture the user's raw request, agent interpretation, scope boundaries, assumptions, unknowns, and confirmation log."
  },
  {
    file: "02-business-requirements.md",
    stage: "business-requirements",
    title: "业务需求",
    prompt:
      "Draft why this should exist, measurable business outcomes, rules, risk, priority, and questions the user can answer."
  },
  {
    file: "03-product-requirements.md",
    stage: "product-requirements",
    title: "产品需求",
    prompt:
      "Draft user roles, tasks, primary workflow, secondary workflows, in-scope functions, and non-goals."
  },
  {
    file: "04-information-architecture.md",
    stage: "information-architecture",
    title: "信息架构需求",
    prompt:
      "Draft information objects, hierarchy, navigation, data fields, grouping, ordering, and content priority."
  },
  {
    file: "05-interaction-matrix.md",
    stage: "interaction-requirements",
    title: "交互矩阵需求",
    prompt:
      "Draft persistent and hidden actions, trigger points, system feedback, permissions, keyboard behavior, and HeroUI component candidates."
  },
  {
    file: "06-state-requirements.md",
    stage: "state-requirements",
    title: "状态需求",
    prompt:
      "Draft default, hover, focus, disabled, loading, empty, error, success, editing, permission, exception, and mobile states."
  },
  {
    file: "07-visual-requirements.md",
    stage: "visual-requirements",
    title: "视觉需求",
    prompt:
      "Draft density, layout, component shape, token usage, responsive behavior, forbidden visual directions, and Pencil/Figma expectations."
  },
  {
    file: "08-engineering-contract.md",
    stage: "engineering-contract",
    title: "工程需求",
    prompt:
      "Draft component mapping, data shape, routes, responsive constraints, Official Component First, HeroUI gap exceptions, and implementation boundaries."
  },
  {
    file: "09-acceptance-contract.md",
    stage: "acceptance-contract",
    title: "验收需求",
    prompt:
      "Draft how to judge correctness, functional checks, visual checks, HeroUI compliance, accessibility, screenshots, commands, and failure criteria."
  },
  {
    file: "10-visual-confirmation-plan.md",
    stage: "visual-confirmation",
    title: "Pencil/Figma 视觉确认计划",
    prompt:
      "Draft required desktop, mobile, component-detail, state-matrix exports and the user approval record required before implementation."
  }
];

const WORKSPACE_FILES_BEFORE_VISUAL = [
  WORKSPACE_STAGE_FILE,
  ...REQUIREMENT_WORKSPACE_ARTIFACTS.filter((artifact) => artifact.file !== "10-visual-confirmation-plan.md").map(
    (artifact) => artifact.file
  )
];

const WORKSPACE_FILES_BEFORE_IMPLEMENTATION = [
  WORKSPACE_STAGE_FILE,
  ...REQUIREMENT_WORKSPACE_ARTIFACTS.map((artifact) => artifact.file)
];

const CHANGE_LAYER_ORDER = [
  {
    key: "business",
    stage: "business-requirements",
    artifact: "02-business-requirements.md",
    patterns: [/业务|指标|收入|成本|规则|风控|目标|优先级/i]
  },
  {
    key: "product",
    stage: "product-requirements",
    artifact: "03-product-requirements.md",
    patterns: [/功能|任务|流程|角色|用户|范围|页面|路径|步骤/i]
  },
  {
    key: "information",
    stage: "information-architecture",
    artifact: "04-information-architecture.md",
    patterns: [/信息|架构|字段|内容|组织|分组|层级|导航|数据对象|栏目/i]
  },
  {
    key: "interaction",
    stage: "interaction-requirements",
    artifact: "05-interaction-matrix.md",
    patterns: [/交互|点击|操作|批量|弹窗|抽屉|筛选|搜索|反馈|隐藏|展示|键盘/i]
  },
  {
    key: "state",
    stage: "state-requirements",
    artifact: "06-state-requirements.md",
    patterns: [/状态|加载|空数据|错误|异常|成功|失败|禁用|编辑态|移动端/i]
  },
  {
    key: "visual",
    stage: "visual-requirements",
    artifact: "07-visual-requirements.md",
    patterns: [/视觉|样式|颜色|密度|布局|间距|圆角|主题|风格|响应式/i]
  },
  {
    key: "engineering",
    stage: "engineering-contract",
    artifact: "08-engineering-contract.md",
    patterns: [/工程|组件|接口|路由|性能|数据结构|实现|代码|HeroUI|Tailwind/i]
  },
  {
    key: "acceptance",
    stage: "acceptance-contract",
    artifact: "09-acceptance-contract.md",
    patterns: [/验收|测试|截图|检查|通过|失败|标准|QA|无障碍/i]
  }
];

const OFFICIAL_CONTEXT = {
  requirements: [
    "React >= 19.0.0",
    "Tailwind CSS >= v4",
    "@heroui/react >= 3.0.0 or @latest",
    "@heroui/styles >= 3.0.0 or @latest"
  ],
  packages: ["@heroui/react", "@heroui/styles"],
  commands: [
    "npx heroui-cli@latest agents-md --react --output AGENTS.md",
    "npx heroui-cli@latest install",
    "npx heroui-cli@latest doctor"
  ],
  styleImportOrder: ['@import "tailwindcss";', '@import "@heroui/styles";'],
  mcpServer: {
    name: "heroui-react",
    command: "npx",
    args: ["-y", "@heroui/react-mcp@latest"]
  },
  docsUrls: [
    "https://heroui.com/react/llms.txt",
    "https://heroui.com/react/llms-components.txt",
    "https://heroui.com/react/llms-patterns.txt",
    "https://heroui.com/react/llms-full.txt"
  ],
  notes: [
    "HeroUI v3 React components work directly after installation and style import.",
    "Do not add HeroUIProvider for React v3; use I18nProvider only when locale setup is required.",
    "Use the official HeroUI MCP server to verify component props, anatomy, source, styles, and theme variables before implementation."
  ]
};

const RAW_COLOR_PATTERN =
  /\b(?:bg|text|border|ring|from|to|via|fill|stroke)-(?:slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-\d{2,3}\b/g;

const SHADCN_IMPORT_PATTERN =
  /(?:@\/components\/ui\/|from\s+["'][^"']*(?:\/|\\)components(?:\/|\\)ui(?:\/|\\)|from\s+["']components\/ui\/)/;

const HANDWRITTEN_UI_PATTERN =
  /(?:class-variance-authority|\bcva\s*\(|@base-ui\/react|@radix-ui\/react|buttonVariants|badgeVariants|cardVariants|data-slot=["'](?:button|card|badge|input|select|tabs|table|sheet|dialog|tooltip|popover|drawer)["'])/;

const TAILWINDUI_SOURCE_PATTERN =
  /(?:@\/(?:catalyst|tailwind-plus|tailwindui|tailwind-ui)\/|from\s+["'][^"']*(?:catalyst-ui-kit|tailwind-plus|tailwindui|tailwind-ui)[^"']*["'])/i;

const HEADLESS_UI_PATTERN = /@headlessui\/react/;

function asTextList(value) {
  if (Array.isArray(value)) {
    return value.map((item) => String(item).toLowerCase());
  }

  if (!value) {
    return [];
  }

  return String(value)
    .split(/[,;\n]/)
    .map((item) => item.trim().toLowerCase())
    .filter(Boolean);
}

function uniqueByName(components) {
  const seen = new Set();
  const result = [];

  for (const [name, rationale] of components) {
    if (seen.has(name)) {
      continue;
    }

    seen.add(name);
    result.push({ name, rationale });
  }

  return result;
}

function hasAnyNeed(needText, matches) {
  return matches.some((term) => needText.includes(term));
}

function detectPaletteFamilies(code) {
  const matches = code.matchAll(RAW_COLOR_PATTERN);
  const counts = new Map();

  for (const match of matches) {
    const family = match[0].split("-")[1];
    counts.set(family, (counts.get(family) ?? 0) + 1);
  }

  return counts;
}

function visualConfirmationApproved(visualConfirmation) {
  return Boolean(
    visualConfirmation?.approved &&
      Array.isArray(visualConfirmation.exportedImages) &&
      visualConfirmation.exportedImages.length > 0
  );
}

function missingVisualExportCategories(visualConfirmation) {
  const names = (visualConfirmation?.exportedImages ?? []).map((image) => String(image).toLowerCase());
  const categories = {
    desktop: names.some((name) => /desktop|1440|wide/.test(name)),
    mobile: names.some((name) => /mobile|390|375|phone/.test(name)),
    componentDetail: names.some((name) => /component|detail|parts|anatomy/.test(name)),
    stateMatrix: names.some((name) => /state|matrix|loading|empty|error|disabled/.test(name))
  };

  return Object.entries(categories)
    .filter(([, present]) => !present)
    .map(([category]) => category);
}

function heroUiGapExceptionComplete(justification) {
  const text = String(justification ?? "").toLowerCase();
  return (
    /missing component/.test(text) &&
    /sources checked/.test(text) &&
    /(agents\.md|llms|mcp|\.heroui-docs|list_components)/.test(text) &&
    /reason/.test(text) &&
    /local scope/.test(text)
  );
}

function normalizePath(filePath) {
  return filePath.replaceAll("\\", "/");
}

function slugify(value = "front-end-surface") {
  const slug = String(value)
    .normalize("NFKD")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .toLowerCase()
    .replace(/[\s_]+/g, "-")
    .replace(/-+/g, "-");

  return slug || "front-end-surface";
}

function requirementWorkspaceRoot(input = {}) {
  const outputRoot = normalizePath(input.outputRoot ?? REQUIREMENT_WORKSPACE_ROOT).replace(/\/$/, "");
  const featureSlug = slugify(input.featureSlug ?? input.featureName ?? "front-end-surface");

  return `${outputRoot}/${featureSlug}`;
}

function workspacePath(root, file) {
  return `${root}/${file}`;
}

function workspaceBasename(path) {
  return normalizePath(path).split("/").pop();
}

function isInsideWorkspace(filePath, root) {
  const normalized = normalizePath(filePath ?? "").replace(/^\.\//, "");
  return normalized === root || normalized.startsWith(`${root}/`);
}

function normalizeArtifacts(artifacts = []) {
  if (Array.isArray(artifacts)) {
    return artifacts.map((artifact) => ({
      file: artifact.file ?? artifact.path ?? artifact.name,
      path: artifact.path ?? artifact.file ?? artifact.name,
      content: String(artifact.content ?? "")
    }));
  }

  return Object.entries(artifacts).map(([file, content]) => ({
    file,
    path: file,
    content: String(content ?? "")
  }));
}

function workspaceFileMap(files = [], root) {
  const map = new Map();
  const outside = [];

  for (const artifact of normalizeArtifacts(files)) {
    const path = normalizePath(artifact.path ?? artifact.file ?? "");
    if (!path) {
      continue;
    }

    if (!isInsideWorkspace(path, root)) {
      outside.push(path);
      continue;
    }

    map.set(workspaceBasename(path), {
      path,
      content: artifact.content
    });
  }

  return { map, outside };
}

function artifactByFile(artifacts) {
  const map = new Map();
  for (const artifact of normalizeArtifacts(artifacts)) {
    if (artifact.file) {
      map.set(artifact.file, artifact);
    }
  }
  return map;
}

function issueForMissingArtifact(file) {
  const codeByFile = {
    "00-requirement-brief.md": "missing-requirement-brief",
    "01-business-requirements.md": "missing-business-requirements",
    "02-product-requirements.md": "missing-product-requirements",
    "03-information-architecture.md": "missing-information-architecture",
    "04-interaction-matrix.md": "missing-interaction-matrix",
    "05-state-requirements.md": "missing-state-requirements",
    "06-visual-requirements.md": "missing-visual-requirements",
    "07-engineering-contract.md": "missing-engineering-contract",
    "08-acceptance-contract.md": "missing-acceptance-contract",
    "09-visual-confirmation-plan.md": "missing-visual-confirmation-plan"
  };

  return {
    severity: "blocker",
    code: codeByFile[file] ?? `missing-${file.replace(/\.md$/, "")}`,
    message: `Missing required requirement artifact: ${file}`
  };
}

function requirementTemplate(featureName, outputDir, artifact) {
  const sectionBody = artifact.requiredSections
    .map((section) => `## ${section}\n\n- 待填写。\n`)
    .join("\n");
  const criteria = artifact.exitCriteria.map((item) => `- [ ] ${item}`).join("\n");
  const heroUiClause =
    artifact.file === "07-engineering-contract.md"
      ? `
## HeroUI硬性条款

- Official Component First: HeroUI 有官方组件时必须使用 \`@heroui/react\`，禁止用 Base UI、Radix UI、CVA 或本地 \`components/ui\` 复刻。
- 开发前必须读取项目 \`AGENTS.md\` 和 \`.heroui-docs/react/\`，并按组件查官方文档或 \`@heroui/react-mcp@latest\`。
- CSS 必须先 \`@import "tailwindcss";\`，再 \`@import "@heroui/styles";\`。
- 若 HeroUI 没有官方组件，必须在“例外记录”写明已检查的官方来源、缺口原因、最小本地实现范围和验收方式。
`
      : "";
  const visualClause =
    artifact.file === "09-visual-confirmation-plan.md"
      ? `
## 图像输出条款

- Pencil/Figma 必须输出桌面完整图、移动完整图、组件细节图、状态矩阵图。
- 组件细节必须展示 anatomy、variants、sizes、icon/label placement、spacing、radius、focus、disabled、loading。
- 状态矩阵必须覆盖 default、hover、focus、disabled、loading、empty、error、success、mobile。
- 用户确认图片前禁止进入前端实现。
`
      : "";
  const acceptanceClause =
    artifact.file === "08-acceptance-contract.md"
      ? `
## 验收方式条款

- 怎么判断做得对不对：每条验收必须能通过命令、截图、DOM/无障碍检查或用户确认验证。
- 必须包含 HeroUI 合规验收：无 \`@/components/ui\`、无 \`@base-ui/react\`、无 \`@radix-ui/react\`、无 \`class-variance-authority\` 复刻官方组件。
- 必须包含官方命令验收：\`npx heroui-cli@latest doctor\`、项目测试、构建、桌面/移动截图。
`
      : "";

  return `# ${featureName} - ${artifact.title}

文件：\`${outputDir}/${artifact.file}\`

层级：${artifact.layer}

目的：${artifact.purpose}

${sectionBody}${heroUiClause}${visualClause}${acceptanceClause}
## 出口标准

${criteria}
`;
}

function stageJsonTemplate({ featureName, featureSlug, root, userRequest }) {
  return `${JSON.stringify(
    {
      schema: "hero-ui-craft.requirement-workspace.v1",
      featureName,
      featureSlug,
      fixedRoot: root,
      currentStage: "rough-intake",
      nextAllowedStage: "requirements",
      userRequest,
      agentOwnsClarification: true,
      gates: {
        beforePencilOrFigma: WORKSPACE_FILES_BEFORE_VISUAL,
        beforeImplementation: WORKSPACE_FILES_BEFORE_IMPLEMENTATION,
        requiresUserApprovedVisualExports: true
      },
      approvals: {
        requirementsApproved: false,
        visualDesignApproved: false,
        implementationApproved: false
      },
      changePolicy:
        "Any requirement change must be recorded under changes/, update impacted artifacts, update this stage file, and regress to the earliest impacted requirement stage."
    },
    null,
    2
  )}\n`;
}

function workspaceMarkdownTemplate({ featureName, userRequest, artifact }) {
  return `# ${featureName} - ${artifact.title}

## Source

- User rough request: ${userRequest || "TBD"}
- Stage: ${artifact.stage}
- Ownership: agent drafts this artifact; the user confirms, corrects, or answers focused questions.

## Agent draft

- Draft the concrete ${artifact.title} from the rough request.
- Do not ask the user to invent structure from scratch.
- Make the best product judgment, then mark assumptions clearly.

## Required content

${artifact.prompt}

## Assumptions to verify

- TBD

## Questions for user confirmation

- TBD

## User confirmation

- Status: pending
- Confirmed by:
- Confirmed at:
- Notes:
`;
}

function initialChangeRecordTemplate({ featureName, userRequest }) {
  return `# ${featureName} - initial intake

## Change type

initial-request

## User rough request

${userRequest || "TBD"}

## Agent responsibility

- Draft the requirement workspace from the rough request.
- Identify unknowns and assumptions.
- Keep the current stage in \`00-stage.json\`.
- Do not proceed to Pencil/Figma until the fixed workspace passes review.
`;
}

function workspaceMissingIssue(file) {
  const codeByFile = {
    [WORKSPACE_STAGE_FILE]: "missing-stage-file",
    "01-rough-request.md": "missing-rough-request",
    "02-business-requirements.md": "missing-business-requirements",
    "03-product-requirements.md": "missing-product-requirements",
    "04-information-architecture.md": "missing-information-architecture",
    "05-interaction-matrix.md": "missing-interaction-matrix",
    "06-state-requirements.md": "missing-state-requirements",
    "07-visual-requirements.md": "missing-visual-requirements",
    "08-engineering-contract.md": "missing-engineering-contract",
    "09-acceptance-contract.md": "missing-acceptance-contract",
    "10-visual-confirmation-plan.md": "missing-visual-confirmation-plan"
  };

  return {
    severity: "blocker",
    code: codeByFile[file] ?? `missing-${file.replace(/\.md|\.json$/, "")}`,
    message: `Missing fixed requirement workspace artifact: ${file}`
  };
}

function parseWorkspaceStage(fileMap) {
  const stage = fileMap.get(WORKSPACE_STAGE_FILE);
  if (!stage) {
    return { stageState: null, issue: null };
  }

  try {
    return { stageState: JSON.parse(stage.content), issue: null };
  } catch {
    return {
      stageState: null,
      issue: {
        severity: "blocker",
        code: "invalid-stage-json",
        message: "00-stage.json must be valid JSON."
      }
    };
  }
}

function requirementsApproved(stageState) {
  return Boolean(
    stageState?.approvals?.requirementsApproved === true ||
      ["visual-design-ready", "visual-awaiting-approval", "implementation-ready", "verification"].includes(
        stageState?.currentStage
      )
  );
}

function stageVisualApproved(stageState, visualConfirmation) {
  return Boolean(stageState?.approvals?.visualDesignApproved === true || visualConfirmationApproved(visualConfirmation));
}

function deriveRequirementWorkspaceStage(fileMap, visualConfirmation, stageState) {
  if (!fileMap.has(WORKSPACE_STAGE_FILE)) {
    return "workspace-missing";
  }

  const hasBeforeVisual = WORKSPACE_FILES_BEFORE_VISUAL.every((file) => fileMap.has(file));
  if (!hasBeforeVisual || !requirementsApproved(stageState)) {
    return "requirements-drafting";
  }

  if (!fileMap.has("10-visual-confirmation-plan.md")) {
    return "visual-design-ready";
  }

  if (!stageVisualApproved(stageState, visualConfirmation)) {
    return "visual-awaiting-approval";
  }

  return "implementation-ready";
}

function detectImpactedLayers(changeRequest, explicitLayers = []) {
  const requested = new Set();
  const text = String(changeRequest ?? "");

  for (const layer of explicitLayers) {
    const normalized = String(layer).toLowerCase();
    const match = CHANGE_LAYER_ORDER.find(
      (candidate) => candidate.key === normalized || candidate.stage === normalized
    );
    if (match) {
      requested.add(match.key);
    }
  }

  for (const layer of CHANGE_LAYER_ORDER) {
    if (layer.patterns.some((pattern) => pattern.test(text))) {
      requested.add(layer.key);
    }
  }

  if (requested.size === 0) {
    requested.add("product");
  }

  return CHANGE_LAYER_ORDER.filter((layer) => requested.has(layer.key));
}

function readAgentManifest() {
  const manifestPath = join(OFFICIAL_AGENT_DOC_ROOT, "manifest.json");
  return JSON.parse(readFileSync(manifestPath, "utf8"));
}

function agentDocumentPath(entry) {
  return join(OFFICIAL_AGENT_DOC_ROOT, entry.path ?? entry.relativePath);
}

function publicAgentDocument(docKey, purpose, index, manifest) {
  const entry = manifest.documents[docKey];
  if (!entry) {
    throw new Error(`Missing HeroUI agent document metadata for ${docKey}`);
  }

  return {
    doc: docKey,
    priority: index + 1,
    purpose,
    path: normalizePath(agentDocumentPath(entry)),
    relativePath: entry.path ?? entry.relativePath,
    source: entry.source,
    bytes: entry.bytes,
    sha256: entry.sha256
  };
}

export function listHeroUiAgentDocs() {
  const manifest = readAgentManifest();

  return {
    library: manifest.library,
    primaryDoc: "agents",
    generated: manifest.generated,
    documents: AGENT_DOC_ORDER.map(([docKey, purpose], index) =>
      publicAgentDocument(docKey, purpose, index, manifest)
    )
  };
}

export function getHeroUiAgentDoc(input = {}) {
  const doc = input.doc ?? "agents";
  const manifest = readAgentManifest();
  const orderEntryIndex = AGENT_DOC_ORDER.findIndex(([docKey]) => docKey === doc);

  if (orderEntryIndex === -1 || !manifest.documents[doc]) {
    throw new Error(`Unknown HeroUI agent doc: ${doc}`);
  }

  const [, purpose] = AGENT_DOC_ORDER[orderEntryIndex];
  const metadata = publicAgentDocument(doc, purpose, orderEntryIndex, manifest);
  const content = readFileSync(metadata.path, "utf8");

  return {
    doc,
    content,
    metadata
  };
}

function getOfficialContext() {
  const agentDocs = listHeroUiAgentDocs();

  return {
    ...OFFICIAL_CONTEXT,
    agentDocs: {
      primaryDoc: agentDocs.primaryDoc,
      generated: agentDocs.generated,
      priority: agentDocs.documents
    }
  };
}

export function selectHeroUiComponents(input = {}) {
  const needs = asTextList(input.needs);
  const needText = needs.join(" ");
  const selected = [];

  for (const rule of COMPONENT_RULES) {
    if (hasAnyNeed(needText, rule.match)) {
      selected.push(...rule.components);
    }
  }

  if (selected.length === 0) {
    selected.push(
      ["Button", "Default command surface."],
      ["Surface", "Theme-aware container primitive."],
      ["Typography", "Consistent text hierarchy."]
    );
  }

  return {
    officialSource: "HeroUI v3 React component catalog",
    components: uniqueByName(selected),
    warnings: [
      "Before coding, query the HeroUI MCP server for docs, props, anatomy, examples, source styles, and theme variables for selected components.",
      "Use @heroui/react component imports instead of local shadcn components.",
      "Do not add HeroUIProvider for React v3; components work after installing packages and importing styles.",
      "Use Tailwind v4 with @import \"tailwindcss\" before @import \"@heroui/styles\"."
    ]
  };
}

export function planVisualConfirmation(input = {}) {
  const components = input.components?.length ? input.components : ["Button", "Surface", "Typography"];
  const targetSurfaces = input.targetSurfaces?.length
    ? input.targetSurfaces
    : ["desktop screen", "mobile screen"];

  return {
    requiresDesignTool: true,
    requiresUserApproval: true,
    acceptedTools: ["Pencil", "Figma"],
    targetSurfaces,
    requiredStates: REQUIRED_VISUAL_STATES,
    pencilGate: [
      "Call get_editor_state(include_schema: true) before any other Pencil tool.",
      "Use batch_design to create the screen, component detail sheet, and state matrix.",
      "Use snapshot_layout to check clipping, overlap, and spacing problems.",
      "Use export_nodes or get_screenshot to produce images for user confirmation."
    ],
    figmaGate: [
      "Load figma-use before any Figma write operation.",
      "Load figma-create-new-file before creating a new Figma file.",
      "Use figma-generate-design only when capturing an existing web page for the first time.",
      "Search existing design system assets before recreating components."
    ],
    requiredExports: [
      "Full-screen desktop image.",
      "Full-screen mobile image.",
      "Component detail sheet showing variants, sizes, anatomy, and spacing.",
      "State matrix for default, hover, focus, disabled, loading, empty, error, success, and mobile."
    ],
    componentChecklist: components.map((component) => ({
      component,
      states: REQUIRED_VISUAL_STATES,
      details: [
        "label and icon placement",
        "spacing and radius",
        "color and contrast",
        "focus ring",
        "disabled opacity",
        "loading treatment",
        "empty/error/success copy placement"
      ]
    }))
  };
}

export function generateRequirementWorkspace(input = {}) {
  const featureName = input.featureName ?? "HeroUI Frontend";
  const featureSlug = slugify(input.featureSlug ?? featureName);
  const userRequest = input.userRequest ?? input.idea ?? "";
  const root = requirementWorkspaceRoot({
    outputRoot: input.outputRoot,
    featureSlug
  });
  const absoluteRoot = input.projectRoot
    ? normalizePath(`${normalizePath(input.projectRoot).replace(/\/$/, "")}/${root}`)
    : undefined;
  const files = [
    {
      path: workspacePath(root, WORKSPACE_STAGE_FILE),
      role: "stage",
      content: stageJsonTemplate({ featureName, featureSlug, root, userRequest })
    },
    ...REQUIREMENT_WORKSPACE_ARTIFACTS.map((artifact) => ({
      path: workspacePath(root, artifact.file),
      role: artifact.stage,
      content: workspaceMarkdownTemplate({ featureName, userRequest, artifact })
    })),
    {
      path: workspacePath(root, "changes/0000-initial-intake.md"),
      role: "change-log",
      content: initialChangeRecordTemplate({ featureName, userRequest })
    }
  ];

  return {
    schema: "hero-ui-craft.requirement-workspace.v1",
    featureName,
    featureSlug,
    fixedRoot: root,
    absoluteRoot,
    stageFile: workspacePath(root, WORKSPACE_STAGE_FILE),
    currentStage: "rough-intake",
    nextAllowedStage: "requirements",
    agentOwnsClarification: true,
    policy: [
      "The user only needs to provide a rough goal, business context, corrections, and confirmations.",
      "The agent must draft information architecture, interaction matrix, state requirements, engineering contract, and acceptance criteria from the rough request.",
      "All requirement artifacts must be written into the fixed project workspace before Pencil/Figma.",
      "Pencil/Figma is blocked until review_requirement_workspace_stage passes for targetStage='visual-design'.",
      "Front-end implementation is blocked until visual exports are approved and review_requirement_workspace_stage passes for targetStage='implementation'."
    ],
    gates: {
      beforePencilOrFigma: WORKSPACE_FILES_BEFORE_VISUAL.map((file) => workspacePath(root, file)),
      beforeImplementation: WORKSPACE_FILES_BEFORE_IMPLEMENTATION.map((file) => workspacePath(root, file))
    },
    files
  };
}

export function reviewRequirementWorkspaceStage(input = {}) {
  const targetStage = input.targetStage ?? "visual-design";
  const root = requirementWorkspaceRoot(input);
  const { map: fileMap, outside } = workspaceFileMap(input.files ?? input.artifacts ?? [], root);
  const requiredFiles =
    targetStage === "implementation" ? WORKSPACE_FILES_BEFORE_IMPLEMENTATION : WORKSPACE_FILES_BEFORE_VISUAL;
  const issues = [];
  const { stageState, issue: stageIssue } = parseWorkspaceStage(fileMap);

  if (outside.length > 0) {
    issues.push({
      severity: "blocker",
      code: "artifact-outside-fixed-workspace",
      message: `Requirement artifacts must live under ${root}. Found outside paths: ${outside.join(", ")}`
    });
  }

  for (const file of requiredFiles) {
    if (!fileMap.has(file)) {
      issues.push(workspaceMissingIssue(file));
    }
  }

  if (stageIssue) {
    issues.push(stageIssue);
  }

  if (fileMap.has(WORKSPACE_STAGE_FILE) && !requirementsApproved(stageState)) {
    issues.push({
      severity: "blocker",
      code: "requirements-not-approved",
      message:
        "The fixed requirement workspace exists, but 00-stage.json does not mark requirementsApproved=true or a visual-design-ready stage."
    });
  }

  if (targetStage === "implementation" && !stageVisualApproved(stageState, input.visualConfirmation)) {
    issues.push({
      severity: "blocker",
      code: "missing-approved-visual-confirmation",
      message:
        "Implementation is blocked until Pencil/Figma desktop, mobile, component-detail, and state-matrix images are exported and approved by the user."
    });
  }

  const currentStage = deriveRequirementWorkspaceStage(fileMap, input.visualConfirmation, stageState);

  return {
    status: issues.length ? "blocked" : "pass",
    fixedRoot: root,
    currentStage,
    targetStage,
    nextAllowedStage: issues.length ? currentStage : targetStage,
    requiredFiles: requiredFiles.map((file) => workspacePath(root, file)),
    issues,
    policy: [
      "Do not start Pencil/Figma unless this review passes for visual-design.",
      "Do not start front-end implementation unless this review passes for implementation.",
      "A loose requirements document outside the fixed workspace does not satisfy the gate.",
      "The stage file is the source of truth for current requirement progress and change handling."
    ]
  };
}

export function planRequirementChange(input = {}) {
  const featureName = input.featureName ?? "HeroUI Frontend";
  const featureSlug = slugify(input.featureSlug ?? featureName);
  const root = requirementWorkspaceRoot({
    outputRoot: input.outputRoot,
    featureSlug
  });
  const changeNumber = Number.isInteger(input.changeNumber) ? input.changeNumber : 1;
  const changeId = String(changeNumber).padStart(4, "0");
  const impactedLayers = detectImpactedLayers(input.changeRequest, input.impactedLayers);
  const earliest = impactedLayers[0];
  const impactedArtifacts = impactedLayers.map((layer) => layer.artifact);
  const invalidates = [];

  if (impactedLayers.some((layer) => layer.key !== "acceptance")) {
    invalidates.push("Pencil/Figma visual approval");
  }

  if (/implementation|verification|done|complete/i.test(String(input.currentStage ?? ""))) {
    invalidates.push("front-end implementation");
  }

  return {
    featureName,
    featureSlug,
    currentStage: input.currentStage ?? "unknown",
    changeRequest: input.changeRequest ?? "",
    changeFilePath: workspacePath(root, `changes/${changeId}-change-request.md`),
    resetToStage: earliest.stage,
    impactedLayers: impactedLayers.map((layer) => layer.key),
    impactedArtifacts,
    invalidates,
    stageUpdate: {
      file: workspacePath(root, WORKSPACE_STAGE_FILE),
      currentStage: earliest.stage,
      nextAllowedStage: "requirements",
      visualDesignApproved: false,
      implementationApproved: false
    },
    requiredActions: [
      "append the change record under changes/ before editing visuals or code",
      "update 00-stage.json with the regressed currentStage and invalidated approvals",
      `update impacted artifacts: ${impactedArtifacts.join(", ")}`,
      "re-run review_requirement_workspace_stage for visual-design before Pencil/Figma",
      "re-export and re-approve Pencil/Figma visuals if any visual, IA, interaction, state, product, or engineering artifact changed",
      "re-run review_requirement_workspace_stage for implementation before code changes"
    ]
  };
}

export function planFrontendRequirementPipeline(input = {}) {
  const outputDir = input.outputDir ?? requirementWorkspaceRoot(input);
  const artifacts = REQUIREMENT_ARTIFACTS.map((artifact, index) => ({
    order: index,
    file: artifact.file,
    path: `${outputDir}/${artifact.file}`,
    title: artifact.title,
    layer: artifact.layer,
    purpose: artifact.purpose,
    requiredSections: artifact.requiredSections,
    exitCriteria: artifact.exitCriteria
  }));

  return {
    principle: "需求是一组被逐层展开、可验证、可实现的约束。",
    idea: input.idea ?? "",
    productType: input.productType ?? "front-end product",
    audience: input.audience ?? "target users",
    primaryWorkflow: input.primaryWorkflow ?? "complete the primary task",
    requirementWorkspace: {
      fixedRoot: requirementWorkspaceRoot(input),
      stageFile: workspacePath(requirementWorkspaceRoot(input), WORKSPACE_STAGE_FILE),
      generator: "generate_requirement_workspace",
      gate: "review_requirement_workspace_stage",
      changePlanner: "plan_requirement_change"
    },
    sequence: REQUIREMENT_SEQUENCE,
    outputDir,
    artifacts,
    gates: {
      beforeVisualDesign: {
        requiresApproval: true,
        requiredArtifacts: REQUIRED_BEFORE_VISUAL,
        rule:
          "固定目录 docs/hero-ui-craft/requirements/<feature-slug>/ 内的需求工作台完成，并通过 review_requirement_workspace_stage(targetStage='visual-design') 后，才允许进入 Pencil/Figma。"
      },
      beforeImplementation: {
        requiresApproval: true,
        requiredArtifacts: REQUIREMENT_FILES,
        rule:
          "Pencil/Figma 导出的桌面、移动、组件细节、状态矩阵图片获得用户确认，并通过 review_requirement_workspace_stage(targetStage='implementation') 后，才允许写前端实现代码。"
      }
    },
    clarificationQuestions: [
      "为什么要做？业务成功如何衡量？",
      "谁使用？他们要完成哪些任务？",
      "内容怎么分组？层级怎么组织？",
      "什么常驻、什么隐藏、点击哪里发生什么？",
      "空数据、加载、错误、异常、编辑、成功、禁用、移动端如何显示？",
      "视觉密度、风格、组件形态、禁止项是什么？",
      "组件如何拆分？数据结构、响应式、路由和性能约束是什么？",
      "怎么判断做得对不对？失败条件是什么？"
    ],
    heroUiRules: [
      "Read official HeroUI React AGENTS.md first, then use .heroui-docs/react or @heroui/react-mcp@latest for component details.",
      "Official Component First: use @heroui/react for every UI primitive HeroUI provides.",
      "No hand-written UI, Base UI, Radix UI, CVA, or local components/ui clone when HeroUI has an official component.",
      "Document every HeroUI gap exception with source checked, reason, scope, and verification.",
      "No Pencil/Figma visual work before the requirement contract passes; no implementation before approved Pencil/Figma images."
    ]
  };
}

export function generateRequirementArtifactTemplates(input = {}) {
  const featureName = input.featureName ?? "HeroUI Frontend";
  const outputDir = input.outputDir ?? "docs/hero-ui";

  return {
    featureName,
    outputDir,
    templates: REQUIREMENT_ARTIFACTS.map((artifact) => ({
      file: artifact.file,
      path: `${outputDir}/${artifact.file}`,
      title: artifact.title,
      layer: artifact.layer,
      content: requirementTemplate(featureName, outputDir, artifact)
    }))
  };
}

export function reviewFrontendRequirementContract(input = {}) {
  const targetStage = input.targetStage ?? "visual-design";
  const artifacts = artifactByFile(input.artifacts ?? []);
  const requiredFiles = targetStage === "implementation" ? REQUIREMENT_FILES : REQUIRED_BEFORE_VISUAL;
  const issues = [];

  for (const file of requiredFiles) {
    if (!artifacts.has(file)) {
      issues.push(issueForMissingArtifact(file));
    }
  }

  const engineering = artifacts.get("07-engineering-contract.md")?.content ?? "";
  if (engineering && !/Official Component First/i.test(engineering)) {
    issues.push({
      severity: "blocker",
      code: "missing-official-component-first",
      message: "Engineering contract must include the Official Component First rule."
    });
  }
  if (engineering && !/@heroui\/react/.test(engineering)) {
    issues.push({
      severity: "blocker",
      code: "missing-heroui-react-contract",
      message: "Engineering contract must require @heroui/react official components."
    });
  }

  const acceptance = artifacts.get("08-acceptance-contract.md")?.content ?? "";
  if (acceptance && !/怎么判断做得对不对|验收/.test(acceptance)) {
    issues.push({
      severity: "blocker",
      code: "missing-acceptance-judgment",
      message: "Acceptance contract must state how to judge whether the work is correct."
    });
  }

  if (targetStage === "implementation") {
    const visual = artifacts.get("09-visual-confirmation-plan.md")?.content ?? "";
    if (!/Pencil\/Figma/.test(visual) || !/组件细节|状态矩阵/.test(visual)) {
      issues.push({
        severity: "blocker",
        code: "missing-visual-confirmation-details",
        message: "Visual confirmation plan must include Pencil/Figma, component detail, and state matrix outputs."
      });
    }
  }

  return {
    status: issues.length ? "blocked" : "pass",
    targetStage,
    nextAllowedStage: issues.length ? "requirements" : targetStage,
    requiredNextArtifact:
      targetStage === "visual-design" ? "09-visual-confirmation-plan.md" : "implementation-verification",
    issues,
    checks: [
      "Requirement layers cover 粗需求 -> 业务需求 -> 产品需求 -> 信息架构需求 -> 交互需求 -> 状态需求 -> 视觉需求 -> 工程需求 -> 验收需求.",
      "Official Component First is present before visual design and implementation.",
      "Pencil/Figma visual confirmation is required before coding.",
      "HeroUI official AGENTS.md, .heroui-docs/react, and @heroui/react-mcp@latest are the source of component truth."
    ]
  };
}

export function generateFrontendVerificationChecklist(input = {}) {
  const viewports = input.viewports?.length ? input.viewports : ["1440x900", "390x844"];
  const interactions = input.interactions?.length ? input.interactions : ["primary workflow"];
  const appType = input.appType ?? "front-end surface";

  return {
    appType,
    sections: [
      {
        title: "Official HeroUI Context",
        items: [
          "Run npx heroui-cli@latest agents-md --react --output AGENTS.md before implementation so the project contains official HeroUI React v3 docs.",
          "Use the heroui-react MCP server with args [-y, @heroui/react-mcp@latest] to check component docs, source, styles, and theme variables.",
          "Install @heroui/react and @heroui/styles, then confirm CSS imports @import \"tailwindcss\" before @import \"@heroui/styles\"."
        ]
      },
      {
        title: "Visual Confirmation",
        items: [
          "Use Pencil or Figma before coding any front-end surface.",
          "Export a full-screen desktop image, full-screen mobile image, and component detail sheet for user approval.",
          "Confirm default, hover, focus, disabled, loading, empty, error, success, and mobile states in the exported images."
        ]
      },
      {
        title: "HeroUI Doctor And Build",
        items: [
          "Run npx heroui-cli@latest doctor in the target project.",
          "Run the project's typecheck, lint, test, and production build commands."
        ]
      },
      {
        title: "Desktop Layout",
        items: viewports
          .filter((viewport) => !viewport.startsWith("3"))
          .map((viewport) => `Capture a screenshot at ${viewport} and confirm hierarchy, density, and text fit.`)
      },
      {
        title: "Mobile Layout",
        items: viewports
          .filter((viewport) => viewport.startsWith("3") || viewport.startsWith("4"))
          .map((viewport) => `Capture a mobile screenshot at ${viewport} and confirm controls remain reachable.`)
      },
      {
        title: "Accessibility",
        items: [
          "Check accessible names for icon-only buttons, drawers, modals, popovers, fields, and form errors.",
          "Confirm keyboard order, visible focus, validation announcements, and contrast."
        ]
      },
      {
        title: "Interactions",
        items: interactions.map((interaction) => `Exercise interaction: ${interaction}.`)
      },
      {
        title: "Quality Review",
        items: [
          "Confirm no shadcn local component imports remain in the changed UI.",
          "Confirm no @nextui-org/react legacy imports remain.",
          "Review screenshots for overlapping text, clipped labels, unstable controls, and unintended one-color dominance."
        ]
      }
    ]
  };
}

export function planHeroUiSystem(input = {}) {
  const productType = input.productType ?? "application";
  const primaryWorkflow = input.primaryWorkflow ?? "complete the main workflow efficiently";
  const componentSelection = selectHeroUiComponents({
    needs: [
      "navigation",
      "filters",
      productType,
      primaryWorkflow,
      "data table",
      "detail drawer",
      "validated form",
      "toast feedback",
      "loading state"
    ]
  });
  const componentNames = componentSelection.components.map((component) => component.name);
  const visualGate = planVisualConfirmation({
    components: componentNames,
    targetSurfaces: input.targetSurfaces
  });

  return {
    intent: {
      productType,
      audience: input.audience ?? "product users",
      primaryWorkflow,
      constraints: input.constraints ?? []
    },
    officialContext: getOfficialContext(),
    requirementPipeline: planFrontendRequirementPipeline({
      idea: input.idea,
      productType,
      audience: input.audience,
      primaryWorkflow
    }),
    visualGate,
    direction:
      "Use HeroUI React v3 primitives and Tailwind v4 styles to build a dense, scannable product surface after component-level visual approval.",
    layout: [
      "Navigation and breadcrumbs",
      "Toolbar with filters and search",
      "Table or structured list",
      "Drawer or modal detail workflow",
      "Toast, alert, skeleton, and error states"
    ],
    components: componentSelection.components,
    heroUiTokens: HERO_UI_SEMANTIC_TOKENS,
    verification: generateFrontendVerificationChecklist({
      appType: productType,
      viewports: ["1440x900", "768x1024", "390x844"],
      interactions: ["keyboard navigation", "filtering", "open Drawer", "submit Form", "show Toast"]
    }).sections.flatMap((section) => section.items),
    antiPatterns: [
      "Do not implement front-end code before Pencil/Figma images have been exported and approved by the user.",
      "Do not import from local shadcn component paths such as @/components/ui/*.",
      "Do not use @nextui-org/react legacy imports.",
      "Do not add HeroUIProvider for React v3 unless the official docs change; use I18nProvider only for locale setup."
    ]
  };
}

export function reviewHeroUiQuality(input = {}) {
  const code = String(input.code ?? "");
  const css = String(input.css ?? "");
  const issues = [];
  const rawColors = [...code.matchAll(RAW_COLOR_PATTERN)].map((match) => match[0]);
  const paletteFamilies = detectPaletteFamilies(code);

  if (!visualConfirmationApproved(input.visualConfirmation)) {
    issues.push({
      severity: "blocker",
      code: "blocked-no-visual-approval",
      message:
        "No approved Pencil/Figma image export was provided. Produce component-detail images and get user approval before coding."
    });
  } else {
    const missingCategories = missingVisualExportCategories(input.visualConfirmation);
    if (missingCategories.length > 0) {
      issues.push({
        severity: "blocker",
        code: "missing-visual-export-categories",
        message: `Pencil/Figma approval is incomplete. Missing export categories: ${missingCategories.join(", ")}.`
      });
    }
  }

  if (input.heroUiGapJustification && !heroUiGapExceptionComplete(input.heroUiGapJustification)) {
    issues.push({
      severity: "blocker",
      code: "incomplete-heroui-gap-exception",
      message:
        "HeroUI gap exceptions must include missing component, official sources checked, reason, and narrow local scope."
    });
  }

  if (SHADCN_IMPORT_PATTERN.test(code)) {
    issues.push({
      severity: "blocker",
      code: "shadcn-import",
      message: "Local shadcn component imports found. Replace with official @heroui/react components."
    });
  }

  if (HANDWRITTEN_UI_PATTERN.test(code) && !input.heroUiGapJustification) {
    issues.push({
      severity: "blocker",
      code: "handwritten-ui-official-available",
      message:
        "Hand-written UI primitives or variant factories found. Use official HeroUI components first; only write local UI when HeroUI has no official component and document the checked source and exception."
    });
  }

  if (TAILWINDUI_SOURCE_PATTERN.test(code)) {
    issues.push({
      severity: "blocker",
      code: "tailwindui-source-or-catalyst-import",
      message:
        "TailwindUI, Tailwind Plus, or Catalyst source imports found. Treat TailwindUI as reference-only and implement visible UI with official @heroui/react components."
    });
  }

  if (HEADLESS_UI_PATTERN.test(code)) {
    issues.push({
      severity: "blocker",
      code: "headlessui-import",
      message:
        "Headless UI imports found. HeroUI React v3 already provides accessible primitives; use official HeroUI components unless a documented gap exception proves otherwise."
    });
  }

  if (/@nextui-org\/react|@nextui-org\/theme/.test(code)) {
    issues.push({
      severity: "high",
      code: "legacy-nextui-package",
      message: "Legacy @nextui-org package import found. Use @heroui/react for HeroUI v3."
    });
  }

  if (/\bHeroUIProvider\b/.test(code)) {
    issues.push({
      severity: "medium",
      code: "obsolete-provider-assumption",
      message:
        "HeroUIProvider detected. HeroUI React v3 does not require a provider after installation and style import; use I18nProvider only for locale setup."
    });
  }

  if (
    (code.includes("@heroui/react") || css.includes("@import \"tailwindcss\"") || css.includes("@import 'tailwindcss'")) &&
    !/@import\s+["']@heroui\/styles["'];/.test(css)
  ) {
    issues.push({
      severity: "high",
      code: "missing-heroui-styles-import",
      message: "Missing @import \"@heroui/styles\" after @import \"tailwindcss\" in the main CSS file."
    });
  }

  if (/@tailwind\s+(?:base|components|utilities)\s*;/.test(css)) {
    issues.push({
      severity: "high",
      code: "legacy-tailwind-directives",
      message:
        "Tailwind v3 @tailwind directives found. HeroUI React v3 expects Tailwind CSS v4 import style: @import \"tailwindcss\"; then @import \"@heroui/styles\";."
    });
  }

  if (rawColors.length > 0) {
    issues.push({
      severity: "medium",
      code: "raw-tailwind-color",
      message: `Raw Tailwind color utilities found: ${[...new Set(rawColors)].join(", ")}. Prefer HeroUI theme tokens and semantic surfaces.`
    });
  }

  if (/\bspace-[xy]-\d+\b/.test(code)) {
    issues.push({
      severity: "medium",
      code: "unsafe-spacing",
      message: "space-y-* or space-x-* detected. Prefer flex/grid with gap-* for predictable composition."
    });
  }

  for (const [family, count] of paletteFamilies) {
    if (count >= 3) {
      issues.push({
        severity: "medium",
        code: "one-note-palette",
        message: `One-note palette risk: ${family} appears ${count} times. Use HeroUI theme variables and mixed semantic surfaces.`
      });
      break;
    }
  }

  if (!/\b(?:max-w-|min-w-0|w-full|grid-cols-|aspect-|overflow-hidden|container|size-)\b/.test(code)) {
    issues.push({
      severity: "medium",
      code: "responsive-constraint",
      message: "No obvious responsive constraint found. Add stable sizing such as max-w-*, min-w-0, grid tracks, aspect ratio, or overflow guards."
    });
  }

  return {
    status: issues.length === 0 ? "pass" : "needs_revision",
    issues,
    recommendations: [
      "Query the official HeroUI MCP server for selected component docs, props, source styles, and theme variables before implementation.",
      "Use @heroui/react imports and Tailwind v4 CSS import order exactly as documented.",
      "Keep Pencil/Figma approval artifacts linked to the implementation notes.",
      "Verify with desktop and mobile screenshots, interaction checks, accessibility checks, and npx heroui-cli@latest doctor."
    ]
  };
}
